// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/admin_service.proto
// Protobuf C++ Version: 5.29.3

#include "proto/admin_service.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace admin {

inline constexpr UpdateServerHealthRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        ishealthy_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR UpdateServerHealthRequest::UpdateServerHealthRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct UpdateServerHealthRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR UpdateServerHealthRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~UpdateServerHealthRequestDefaultTypeInternal() {}
  union {
    UpdateServerHealthRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 UpdateServerHealthRequestDefaultTypeInternal _UpdateServerHealthRequest_default_instance_;

inline constexpr ServerInfo::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        host_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        port_{0u},
        ishealthy_{false},
        last_health_check_unix_seconds_{::int64_t{0}},
        request_count_{::int64_t{0}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ServerInfo::ServerInfo(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ServerInfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ServerInfoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ServerInfoDefaultTypeInternal() {}
  union {
    ServerInfo _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ServerInfoDefaultTypeInternal _ServerInfo_default_instance_;

inline constexpr RemoveServerRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR RemoveServerRequest::RemoveServerRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct RemoveServerRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RemoveServerRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RemoveServerRequestDefaultTypeInternal() {}
  union {
    RemoveServerRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RemoveServerRequestDefaultTypeInternal _RemoveServerRequest_default_instance_;

inline constexpr AddServerResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR AddServerResponse::AddServerResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct AddServerResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AddServerResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AddServerResponseDefaultTypeInternal() {}
  union {
    AddServerResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AddServerResponseDefaultTypeInternal _AddServerResponse_default_instance_;

inline constexpr ListServersResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : servers_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ListServersResponse::ListServersResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ListServersResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ListServersResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ListServersResponseDefaultTypeInternal() {}
  union {
    ListServersResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ListServersResponseDefaultTypeInternal _ListServersResponse_default_instance_;
}  // namespace admin
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_proto_2fadmin_5fservice_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_proto_2fadmin_5fservice_2eproto = nullptr;
const ::uint32_t
    TableStruct_proto_2fadmin_5fservice_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::admin::ListServersResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::admin::ListServersResponse, _impl_.servers_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::admin::ServerInfo, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::admin::ServerInfo, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::admin::ServerInfo, _impl_.host_),
        PROTOBUF_FIELD_OFFSET(::admin::ServerInfo, _impl_.port_),
        PROTOBUF_FIELD_OFFSET(::admin::ServerInfo, _impl_.ishealthy_),
        PROTOBUF_FIELD_OFFSET(::admin::ServerInfo, _impl_.last_health_check_unix_seconds_),
        PROTOBUF_FIELD_OFFSET(::admin::ServerInfo, _impl_.request_count_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::admin::UpdateServerHealthRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::admin::UpdateServerHealthRequest, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::admin::UpdateServerHealthRequest, _impl_.ishealthy_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::admin::AddServerResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::admin::AddServerResponse, _impl_.id_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::admin::RemoveServerRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::admin::RemoveServerRequest, _impl_.id_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::admin::ListServersResponse)},
        {9, -1, -1, sizeof(::admin::ServerInfo)},
        {23, -1, -1, sizeof(::admin::UpdateServerHealthRequest)},
        {33, -1, -1, sizeof(::admin::AddServerResponse)},
        {42, -1, -1, sizeof(::admin::RemoveServerRequest)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::admin::_ListServersResponse_default_instance_._instance,
    &::admin::_ServerInfo_default_instance_._instance,
    &::admin::_UpdateServerHealthRequest_default_instance_._instance,
    &::admin::_AddServerResponse_default_instance_._instance,
    &::admin::_RemoveServerRequest_default_instance_._instance,
};
const char descriptor_table_protodef_proto_2fadmin_5fservice_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\031proto/admin_service.proto\022\005admin\032\033goog"
    "le/protobuf/empty.proto\"9\n\023ListServersRe"
    "sponse\022\"\n\007servers\030\001 \003(\0132\021.admin.ServerIn"
    "fo\"\206\001\n\nServerInfo\022\n\n\002id\030\001 \001(\t\022\014\n\004host\030\002 "
    "\001(\t\022\014\n\004port\030\003 \001(\r\022\021\n\tisHealthy\030\004 \001(\010\022&\n\036"
    "last_health_check_unix_seconds\030\005 \001(\003\022\025\n\r"
    "request_count\030\006 \001(\003\":\n\031UpdateServerHealt"
    "hRequest\022\n\n\002id\030\001 \001(\t\022\021\n\tisHealthy\030\002 \001(\010\""
    "\037\n\021AddServerResponse\022\n\n\002id\030\001 \001(\t\"!\n\023Remo"
    "veServerRequest\022\n\n\002id\030\001 \001(\t2\244\002\n\014AdminSer"
    "vice\022A\n\013ListServers\022\026.google.protobuf.Em"
    "pty\032\032.admin.ListServersResponse\022N\n\022Updat"
    "eServerHealth\022 .admin.UpdateServerHealth"
    "Request\032\026.google.protobuf.Empty\022=\n\tAddSe"
    "rver\022\026.google.protobuf.Empty\032\030.admin.Add"
    "ServerResponse\022B\n\014RemoveServer\022\032.admin.R"
    "emoveServerRequest\032\026.google.protobuf.Emp"
    "tyb\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_proto_2fadmin_5fservice_2eproto_deps[1] =
    {
        &::descriptor_table_google_2fprotobuf_2fempty_2eproto,
};
static ::absl::once_flag descriptor_table_proto_2fadmin_5fservice_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_proto_2fadmin_5fservice_2eproto = {
    false,
    false,
    690,
    descriptor_table_protodef_proto_2fadmin_5fservice_2eproto,
    "proto/admin_service.proto",
    &descriptor_table_proto_2fadmin_5fservice_2eproto_once,
    descriptor_table_proto_2fadmin_5fservice_2eproto_deps,
    1,
    5,
    schemas,
    file_default_instances,
    TableStruct_proto_2fadmin_5fservice_2eproto::offsets,
    file_level_enum_descriptors_proto_2fadmin_5fservice_2eproto,
    file_level_service_descriptors_proto_2fadmin_5fservice_2eproto,
};
namespace admin {
// ===================================================================

class ListServersResponse::_Internal {
 public:
};

ListServersResponse::ListServersResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:admin.ListServersResponse)
}
inline PROTOBUF_NDEBUG_INLINE ListServersResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::admin::ListServersResponse& from_msg)
      : servers_{visibility, arena, from.servers_},
        _cached_size_{0} {}

ListServersResponse::ListServersResponse(
    ::google::protobuf::Arena* arena,
    const ListServersResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ListServersResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:admin.ListServersResponse)
}
inline PROTOBUF_NDEBUG_INLINE ListServersResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : servers_{visibility, arena},
        _cached_size_{0} {}

inline void ListServersResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ListServersResponse::~ListServersResponse() {
  // @@protoc_insertion_point(destructor:admin.ListServersResponse)
  SharedDtor(*this);
}
inline void ListServersResponse::SharedDtor(MessageLite& self) {
  ListServersResponse& this_ = static_cast<ListServersResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* ListServersResponse::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ListServersResponse(arena);
}
constexpr auto ListServersResponse::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(ListServersResponse, _impl_.servers_) +
          decltype(ListServersResponse::_impl_.servers_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(ListServersResponse), alignof(ListServersResponse), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&ListServersResponse::PlacementNew_,
                                 sizeof(ListServersResponse),
                                 alignof(ListServersResponse));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull ListServersResponse::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_ListServersResponse_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &ListServersResponse::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<ListServersResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &ListServersResponse::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<ListServersResponse>(), &ListServersResponse::ByteSizeLong,
            &ListServersResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(ListServersResponse, _impl_._cached_size_),
        false,
    },
    &ListServersResponse::kDescriptorMethods,
    &descriptor_table_proto_2fadmin_5fservice_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* ListServersResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> ListServersResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::admin::ListServersResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .admin.ServerInfo servers = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ListServersResponse, _impl_.servers_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .admin.ServerInfo servers = 1;
    {PROTOBUF_FIELD_OFFSET(ListServersResponse, _impl_.servers_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::admin::ServerInfo>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void ListServersResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:admin.ListServersResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.servers_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ListServersResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ListServersResponse& this_ = static_cast<const ListServersResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ListServersResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ListServersResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:admin.ListServersResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // repeated .admin.ServerInfo servers = 1;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_servers_size());
               i < n; i++) {
            const auto& repfield = this_._internal_servers().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    1, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:admin.ListServersResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ListServersResponse::ByteSizeLong(const MessageLite& base) {
          const ListServersResponse& this_ = static_cast<const ListServersResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ListServersResponse::ByteSizeLong() const {
          const ListServersResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:admin.ListServersResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .admin.ServerInfo servers = 1;
            {
              total_size += 1UL * this_._internal_servers_size();
              for (const auto& msg : this_._internal_servers()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ListServersResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ListServersResponse*>(&to_msg);
  auto& from = static_cast<const ListServersResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:admin.ListServersResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_servers()->MergeFrom(
      from._internal_servers());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ListServersResponse::CopyFrom(const ListServersResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:admin.ListServersResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ListServersResponse::InternalSwap(ListServersResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.servers_.InternalSwap(&other->_impl_.servers_);
}

::google::protobuf::Metadata ListServersResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ServerInfo::_Internal {
 public:
};

ServerInfo::ServerInfo(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:admin.ServerInfo)
}
inline PROTOBUF_NDEBUG_INLINE ServerInfo::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::admin::ServerInfo& from_msg)
      : id_(arena, from.id_),
        host_(arena, from.host_),
        _cached_size_{0} {}

ServerInfo::ServerInfo(
    ::google::protobuf::Arena* arena,
    const ServerInfo& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ServerInfo* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, port_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, port_),
           offsetof(Impl_, request_count_) -
               offsetof(Impl_, port_) +
               sizeof(Impl_::request_count_));

  // @@protoc_insertion_point(copy_constructor:admin.ServerInfo)
}
inline PROTOBUF_NDEBUG_INLINE ServerInfo::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : id_(arena),
        host_(arena),
        _cached_size_{0} {}

inline void ServerInfo::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, port_),
           0,
           offsetof(Impl_, request_count_) -
               offsetof(Impl_, port_) +
               sizeof(Impl_::request_count_));
}
ServerInfo::~ServerInfo() {
  // @@protoc_insertion_point(destructor:admin.ServerInfo)
  SharedDtor(*this);
}
inline void ServerInfo::SharedDtor(MessageLite& self) {
  ServerInfo& this_ = static_cast<ServerInfo&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.id_.Destroy();
  this_._impl_.host_.Destroy();
  this_._impl_.~Impl_();
}

inline void* ServerInfo::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) ServerInfo(arena);
}
constexpr auto ServerInfo::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ServerInfo),
                                            alignof(ServerInfo));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull ServerInfo::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_ServerInfo_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &ServerInfo::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<ServerInfo>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &ServerInfo::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<ServerInfo>(), &ServerInfo::ByteSizeLong,
            &ServerInfo::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(ServerInfo, _impl_._cached_size_),
        false,
    },
    &ServerInfo::kDescriptorMethods,
    &descriptor_table_proto_2fadmin_5fservice_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* ServerInfo::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 6, 0, 31, 2> ServerInfo::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    6, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967232,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::admin::ServerInfo>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(ServerInfo, _impl_.id_)}},
    // string host = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(ServerInfo, _impl_.host_)}},
    // uint32 port = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(ServerInfo, _impl_.port_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(ServerInfo, _impl_.port_)}},
    // bool isHealthy = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(ServerInfo, _impl_.ishealthy_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(ServerInfo, _impl_.ishealthy_)}},
    // int64 last_health_check_unix_seconds = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(ServerInfo, _impl_.last_health_check_unix_seconds_), 63>(),
     {40, 63, 0, PROTOBUF_FIELD_OFFSET(ServerInfo, _impl_.last_health_check_unix_seconds_)}},
    // int64 request_count = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(ServerInfo, _impl_.request_count_), 63>(),
     {48, 63, 0, PROTOBUF_FIELD_OFFSET(ServerInfo, _impl_.request_count_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // string id = 1;
    {PROTOBUF_FIELD_OFFSET(ServerInfo, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string host = 2;
    {PROTOBUF_FIELD_OFFSET(ServerInfo, _impl_.host_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // uint32 port = 3;
    {PROTOBUF_FIELD_OFFSET(ServerInfo, _impl_.port_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // bool isHealthy = 4;
    {PROTOBUF_FIELD_OFFSET(ServerInfo, _impl_.ishealthy_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // int64 last_health_check_unix_seconds = 5;
    {PROTOBUF_FIELD_OFFSET(ServerInfo, _impl_.last_health_check_unix_seconds_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
    // int64 request_count = 6;
    {PROTOBUF_FIELD_OFFSET(ServerInfo, _impl_.request_count_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
    "\20\2\4\0\0\0\0\0"
    "admin.ServerInfo"
    "id"
    "host"
  }},
};

PROTOBUF_NOINLINE void ServerInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:admin.ServerInfo)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.id_.ClearToEmpty();
  _impl_.host_.ClearToEmpty();
  ::memset(&_impl_.port_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.request_count_) -
      reinterpret_cast<char*>(&_impl_.port_)) + sizeof(_impl_.request_count_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* ServerInfo::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const ServerInfo& this_ = static_cast<const ServerInfo&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* ServerInfo::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const ServerInfo& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:admin.ServerInfo)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string id = 1;
          if (!this_._internal_id().empty()) {
            const std::string& _s = this_._internal_id();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "admin.ServerInfo.id");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // string host = 2;
          if (!this_._internal_host().empty()) {
            const std::string& _s = this_._internal_host();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "admin.ServerInfo.host");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // uint32 port = 3;
          if (this_._internal_port() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                3, this_._internal_port(), target);
          }

          // bool isHealthy = 4;
          if (this_._internal_ishealthy() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                4, this_._internal_ishealthy(), target);
          }

          // int64 last_health_check_unix_seconds = 5;
          if (this_._internal_last_health_check_unix_seconds() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt64ToArrayWithField<5>(
                    stream, this_._internal_last_health_check_unix_seconds(), target);
          }

          // int64 request_count = 6;
          if (this_._internal_request_count() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt64ToArrayWithField<6>(
                    stream, this_._internal_request_count(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:admin.ServerInfo)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t ServerInfo::ByteSizeLong(const MessageLite& base) {
          const ServerInfo& this_ = static_cast<const ServerInfo&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t ServerInfo::ByteSizeLong() const {
          const ServerInfo& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:admin.ServerInfo)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string id = 1;
            if (!this_._internal_id().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_id());
            }
            // string host = 2;
            if (!this_._internal_host().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_host());
            }
            // uint32 port = 3;
            if (this_._internal_port() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_port());
            }
            // bool isHealthy = 4;
            if (this_._internal_ishealthy() != 0) {
              total_size += 2;
            }
            // int64 last_health_check_unix_seconds = 5;
            if (this_._internal_last_health_check_unix_seconds() != 0) {
              total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
                  this_._internal_last_health_check_unix_seconds());
            }
            // int64 request_count = 6;
            if (this_._internal_request_count() != 0) {
              total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
                  this_._internal_request_count());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void ServerInfo::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ServerInfo*>(&to_msg);
  auto& from = static_cast<const ServerInfo&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:admin.ServerInfo)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_id().empty()) {
    _this->_internal_set_id(from._internal_id());
  }
  if (!from._internal_host().empty()) {
    _this->_internal_set_host(from._internal_host());
  }
  if (from._internal_port() != 0) {
    _this->_impl_.port_ = from._impl_.port_;
  }
  if (from._internal_ishealthy() != 0) {
    _this->_impl_.ishealthy_ = from._impl_.ishealthy_;
  }
  if (from._internal_last_health_check_unix_seconds() != 0) {
    _this->_impl_.last_health_check_unix_seconds_ = from._impl_.last_health_check_unix_seconds_;
  }
  if (from._internal_request_count() != 0) {
    _this->_impl_.request_count_ = from._impl_.request_count_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ServerInfo::CopyFrom(const ServerInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:admin.ServerInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ServerInfo::InternalSwap(ServerInfo* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.id_, &other->_impl_.id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.host_, &other->_impl_.host_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ServerInfo, _impl_.request_count_)
      + sizeof(ServerInfo::_impl_.request_count_)
      - PROTOBUF_FIELD_OFFSET(ServerInfo, _impl_.port_)>(
          reinterpret_cast<char*>(&_impl_.port_),
          reinterpret_cast<char*>(&other->_impl_.port_));
}

::google::protobuf::Metadata ServerInfo::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class UpdateServerHealthRequest::_Internal {
 public:
};

UpdateServerHealthRequest::UpdateServerHealthRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:admin.UpdateServerHealthRequest)
}
inline PROTOBUF_NDEBUG_INLINE UpdateServerHealthRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::admin::UpdateServerHealthRequest& from_msg)
      : id_(arena, from.id_),
        _cached_size_{0} {}

UpdateServerHealthRequest::UpdateServerHealthRequest(
    ::google::protobuf::Arena* arena,
    const UpdateServerHealthRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  UpdateServerHealthRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.ishealthy_ = from._impl_.ishealthy_;

  // @@protoc_insertion_point(copy_constructor:admin.UpdateServerHealthRequest)
}
inline PROTOBUF_NDEBUG_INLINE UpdateServerHealthRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : id_(arena),
        _cached_size_{0} {}

inline void UpdateServerHealthRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.ishealthy_ = {};
}
UpdateServerHealthRequest::~UpdateServerHealthRequest() {
  // @@protoc_insertion_point(destructor:admin.UpdateServerHealthRequest)
  SharedDtor(*this);
}
inline void UpdateServerHealthRequest::SharedDtor(MessageLite& self) {
  UpdateServerHealthRequest& this_ = static_cast<UpdateServerHealthRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.id_.Destroy();
  this_._impl_.~Impl_();
}

inline void* UpdateServerHealthRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) UpdateServerHealthRequest(arena);
}
constexpr auto UpdateServerHealthRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(UpdateServerHealthRequest),
                                            alignof(UpdateServerHealthRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull UpdateServerHealthRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_UpdateServerHealthRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &UpdateServerHealthRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<UpdateServerHealthRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &UpdateServerHealthRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<UpdateServerHealthRequest>(), &UpdateServerHealthRequest::ByteSizeLong,
            &UpdateServerHealthRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(UpdateServerHealthRequest, _impl_._cached_size_),
        false,
    },
    &UpdateServerHealthRequest::kDescriptorMethods,
    &descriptor_table_proto_2fadmin_5fservice_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* UpdateServerHealthRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 42, 2> UpdateServerHealthRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::admin::UpdateServerHealthRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bool isHealthy = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(UpdateServerHealthRequest, _impl_.ishealthy_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(UpdateServerHealthRequest, _impl_.ishealthy_)}},
    // string id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(UpdateServerHealthRequest, _impl_.id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string id = 1;
    {PROTOBUF_FIELD_OFFSET(UpdateServerHealthRequest, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bool isHealthy = 2;
    {PROTOBUF_FIELD_OFFSET(UpdateServerHealthRequest, _impl_.ishealthy_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
    "\37\2\0\0\0\0\0\0"
    "admin.UpdateServerHealthRequest"
    "id"
  }},
};

PROTOBUF_NOINLINE void UpdateServerHealthRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:admin.UpdateServerHealthRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.id_.ClearToEmpty();
  _impl_.ishealthy_ = false;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* UpdateServerHealthRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const UpdateServerHealthRequest& this_ = static_cast<const UpdateServerHealthRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* UpdateServerHealthRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const UpdateServerHealthRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:admin.UpdateServerHealthRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string id = 1;
          if (!this_._internal_id().empty()) {
            const std::string& _s = this_._internal_id();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "admin.UpdateServerHealthRequest.id");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // bool isHealthy = 2;
          if (this_._internal_ishealthy() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                2, this_._internal_ishealthy(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:admin.UpdateServerHealthRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t UpdateServerHealthRequest::ByteSizeLong(const MessageLite& base) {
          const UpdateServerHealthRequest& this_ = static_cast<const UpdateServerHealthRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t UpdateServerHealthRequest::ByteSizeLong() const {
          const UpdateServerHealthRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:admin.UpdateServerHealthRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string id = 1;
            if (!this_._internal_id().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_id());
            }
            // bool isHealthy = 2;
            if (this_._internal_ishealthy() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void UpdateServerHealthRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<UpdateServerHealthRequest*>(&to_msg);
  auto& from = static_cast<const UpdateServerHealthRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:admin.UpdateServerHealthRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_id().empty()) {
    _this->_internal_set_id(from._internal_id());
  }
  if (from._internal_ishealthy() != 0) {
    _this->_impl_.ishealthy_ = from._impl_.ishealthy_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void UpdateServerHealthRequest::CopyFrom(const UpdateServerHealthRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:admin.UpdateServerHealthRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void UpdateServerHealthRequest::InternalSwap(UpdateServerHealthRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.id_, &other->_impl_.id_, arena);
        swap(_impl_.ishealthy_, other->_impl_.ishealthy_);
}

::google::protobuf::Metadata UpdateServerHealthRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class AddServerResponse::_Internal {
 public:
};

AddServerResponse::AddServerResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:admin.AddServerResponse)
}
inline PROTOBUF_NDEBUG_INLINE AddServerResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::admin::AddServerResponse& from_msg)
      : id_(arena, from.id_),
        _cached_size_{0} {}

AddServerResponse::AddServerResponse(
    ::google::protobuf::Arena* arena,
    const AddServerResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  AddServerResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:admin.AddServerResponse)
}
inline PROTOBUF_NDEBUG_INLINE AddServerResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : id_(arena),
        _cached_size_{0} {}

inline void AddServerResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
AddServerResponse::~AddServerResponse() {
  // @@protoc_insertion_point(destructor:admin.AddServerResponse)
  SharedDtor(*this);
}
inline void AddServerResponse::SharedDtor(MessageLite& self) {
  AddServerResponse& this_ = static_cast<AddServerResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.id_.Destroy();
  this_._impl_.~Impl_();
}

inline void* AddServerResponse::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) AddServerResponse(arena);
}
constexpr auto AddServerResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(AddServerResponse),
                                            alignof(AddServerResponse));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull AddServerResponse::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_AddServerResponse_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &AddServerResponse::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<AddServerResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &AddServerResponse::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<AddServerResponse>(), &AddServerResponse::ByteSizeLong,
            &AddServerResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(AddServerResponse, _impl_._cached_size_),
        false,
    },
    &AddServerResponse::kDescriptorMethods,
    &descriptor_table_proto_2fadmin_5fservice_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* AddServerResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 34, 2> AddServerResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::admin::AddServerResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(AddServerResponse, _impl_.id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string id = 1;
    {PROTOBUF_FIELD_OFFSET(AddServerResponse, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\27\2\0\0\0\0\0\0"
    "admin.AddServerResponse"
    "id"
  }},
};

PROTOBUF_NOINLINE void AddServerResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:admin.AddServerResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.id_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* AddServerResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const AddServerResponse& this_ = static_cast<const AddServerResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* AddServerResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const AddServerResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:admin.AddServerResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string id = 1;
          if (!this_._internal_id().empty()) {
            const std::string& _s = this_._internal_id();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "admin.AddServerResponse.id");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:admin.AddServerResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t AddServerResponse::ByteSizeLong(const MessageLite& base) {
          const AddServerResponse& this_ = static_cast<const AddServerResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t AddServerResponse::ByteSizeLong() const {
          const AddServerResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:admin.AddServerResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // string id = 1;
            if (!this_._internal_id().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_id());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void AddServerResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<AddServerResponse*>(&to_msg);
  auto& from = static_cast<const AddServerResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:admin.AddServerResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_id().empty()) {
    _this->_internal_set_id(from._internal_id());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void AddServerResponse::CopyFrom(const AddServerResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:admin.AddServerResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void AddServerResponse::InternalSwap(AddServerResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.id_, &other->_impl_.id_, arena);
}

::google::protobuf::Metadata AddServerResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class RemoveServerRequest::_Internal {
 public:
};

RemoveServerRequest::RemoveServerRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:admin.RemoveServerRequest)
}
inline PROTOBUF_NDEBUG_INLINE RemoveServerRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::admin::RemoveServerRequest& from_msg)
      : id_(arena, from.id_),
        _cached_size_{0} {}

RemoveServerRequest::RemoveServerRequest(
    ::google::protobuf::Arena* arena,
    const RemoveServerRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  RemoveServerRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:admin.RemoveServerRequest)
}
inline PROTOBUF_NDEBUG_INLINE RemoveServerRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : id_(arena),
        _cached_size_{0} {}

inline void RemoveServerRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
RemoveServerRequest::~RemoveServerRequest() {
  // @@protoc_insertion_point(destructor:admin.RemoveServerRequest)
  SharedDtor(*this);
}
inline void RemoveServerRequest::SharedDtor(MessageLite& self) {
  RemoveServerRequest& this_ = static_cast<RemoveServerRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.id_.Destroy();
  this_._impl_.~Impl_();
}

inline void* RemoveServerRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) RemoveServerRequest(arena);
}
constexpr auto RemoveServerRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(RemoveServerRequest),
                                            alignof(RemoveServerRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull RemoveServerRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_RemoveServerRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &RemoveServerRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<RemoveServerRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &RemoveServerRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<RemoveServerRequest>(), &RemoveServerRequest::ByteSizeLong,
            &RemoveServerRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(RemoveServerRequest, _impl_._cached_size_),
        false,
    },
    &RemoveServerRequest::kDescriptorMethods,
    &descriptor_table_proto_2fadmin_5fservice_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* RemoveServerRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 36, 2> RemoveServerRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::admin::RemoveServerRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(RemoveServerRequest, _impl_.id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string id = 1;
    {PROTOBUF_FIELD_OFFSET(RemoveServerRequest, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\31\2\0\0\0\0\0\0"
    "admin.RemoveServerRequest"
    "id"
  }},
};

PROTOBUF_NOINLINE void RemoveServerRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:admin.RemoveServerRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.id_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* RemoveServerRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const RemoveServerRequest& this_ = static_cast<const RemoveServerRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* RemoveServerRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const RemoveServerRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:admin.RemoveServerRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string id = 1;
          if (!this_._internal_id().empty()) {
            const std::string& _s = this_._internal_id();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "admin.RemoveServerRequest.id");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:admin.RemoveServerRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t RemoveServerRequest::ByteSizeLong(const MessageLite& base) {
          const RemoveServerRequest& this_ = static_cast<const RemoveServerRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t RemoveServerRequest::ByteSizeLong() const {
          const RemoveServerRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:admin.RemoveServerRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // string id = 1;
            if (!this_._internal_id().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_id());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void RemoveServerRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<RemoveServerRequest*>(&to_msg);
  auto& from = static_cast<const RemoveServerRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:admin.RemoveServerRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_id().empty()) {
    _this->_internal_set_id(from._internal_id());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RemoveServerRequest::CopyFrom(const RemoveServerRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:admin.RemoveServerRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void RemoveServerRequest::InternalSwap(RemoveServerRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.id_, &other->_impl_.id_, arena);
}

::google::protobuf::Metadata RemoveServerRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace admin
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_proto_2fadmin_5fservice_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
