// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: proto/load_balancer.proto
#ifndef GRPC_proto_2fload_5fbalancer_2eproto__INCLUDED
#define GRPC_proto_2fload_5fbalancer_2eproto__INCLUDED

#include "proto/load_balancer.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace loadbalancer {

class LoadBalancerService final {
 public:
  static constexpr char const* service_full_name() {
    return "loadbalancer.LoadBalancerService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status HandleRequest(::grpc::ClientContext* context, const ::loadbalancer::Request& request, ::loadbalancer::Response* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::loadbalancer::Response>> AsyncHandleRequest(::grpc::ClientContext* context, const ::loadbalancer::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::loadbalancer::Response>>(AsyncHandleRequestRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::loadbalancer::Response>> PrepareAsyncHandleRequest(::grpc::ClientContext* context, const ::loadbalancer::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::loadbalancer::Response>>(PrepareAsyncHandleRequestRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void HandleRequest(::grpc::ClientContext* context, const ::loadbalancer::Request* request, ::loadbalancer::Response* response, std::function<void(::grpc::Status)>) = 0;
      virtual void HandleRequest(::grpc::ClientContext* context, const ::loadbalancer::Request* request, ::loadbalancer::Response* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::loadbalancer::Response>* AsyncHandleRequestRaw(::grpc::ClientContext* context, const ::loadbalancer::Request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::loadbalancer::Response>* PrepareAsyncHandleRequestRaw(::grpc::ClientContext* context, const ::loadbalancer::Request& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status HandleRequest(::grpc::ClientContext* context, const ::loadbalancer::Request& request, ::loadbalancer::Response* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::loadbalancer::Response>> AsyncHandleRequest(::grpc::ClientContext* context, const ::loadbalancer::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::loadbalancer::Response>>(AsyncHandleRequestRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::loadbalancer::Response>> PrepareAsyncHandleRequest(::grpc::ClientContext* context, const ::loadbalancer::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::loadbalancer::Response>>(PrepareAsyncHandleRequestRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void HandleRequest(::grpc::ClientContext* context, const ::loadbalancer::Request* request, ::loadbalancer::Response* response, std::function<void(::grpc::Status)>) override;
      void HandleRequest(::grpc::ClientContext* context, const ::loadbalancer::Request* request, ::loadbalancer::Response* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::loadbalancer::Response>* AsyncHandleRequestRaw(::grpc::ClientContext* context, const ::loadbalancer::Request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::loadbalancer::Response>* PrepareAsyncHandleRequestRaw(::grpc::ClientContext* context, const ::loadbalancer::Request& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_HandleRequest_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status HandleRequest(::grpc::ServerContext* context, const ::loadbalancer::Request* request, ::loadbalancer::Response* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_HandleRequest : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_HandleRequest() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_HandleRequest() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status HandleRequest(::grpc::ServerContext* /*context*/, const ::loadbalancer::Request* /*request*/, ::loadbalancer::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestHandleRequest(::grpc::ServerContext* context, ::loadbalancer::Request* request, ::grpc::ServerAsyncResponseWriter< ::loadbalancer::Response>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_HandleRequest<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_HandleRequest : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_HandleRequest() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::loadbalancer::Request, ::loadbalancer::Response>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::loadbalancer::Request* request, ::loadbalancer::Response* response) { return this->HandleRequest(context, request, response); }));}
    void SetMessageAllocatorFor_HandleRequest(
        ::grpc::MessageAllocator< ::loadbalancer::Request, ::loadbalancer::Response>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::loadbalancer::Request, ::loadbalancer::Response>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_HandleRequest() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status HandleRequest(::grpc::ServerContext* /*context*/, const ::loadbalancer::Request* /*request*/, ::loadbalancer::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* HandleRequest(
      ::grpc::CallbackServerContext* /*context*/, const ::loadbalancer::Request* /*request*/, ::loadbalancer::Response* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_HandleRequest<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_HandleRequest : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_HandleRequest() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_HandleRequest() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status HandleRequest(::grpc::ServerContext* /*context*/, const ::loadbalancer::Request* /*request*/, ::loadbalancer::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_HandleRequest : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_HandleRequest() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_HandleRequest() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status HandleRequest(::grpc::ServerContext* /*context*/, const ::loadbalancer::Request* /*request*/, ::loadbalancer::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestHandleRequest(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_HandleRequest : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_HandleRequest() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->HandleRequest(context, request, response); }));
    }
    ~WithRawCallbackMethod_HandleRequest() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status HandleRequest(::grpc::ServerContext* /*context*/, const ::loadbalancer::Request* /*request*/, ::loadbalancer::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* HandleRequest(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_HandleRequest : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_HandleRequest() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::loadbalancer::Request, ::loadbalancer::Response>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::loadbalancer::Request, ::loadbalancer::Response>* streamer) {
                       return this->StreamedHandleRequest(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_HandleRequest() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status HandleRequest(::grpc::ServerContext* /*context*/, const ::loadbalancer::Request* /*request*/, ::loadbalancer::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedHandleRequest(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::loadbalancer::Request,::loadbalancer::Response>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_HandleRequest<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_HandleRequest<Service > StreamedService;
};

}  // namespace loadbalancer


#endif  // GRPC_proto_2fload_5fbalancer_2eproto__INCLUDED
